name: aibs
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - pip
  - arviz
  - matplotlib
  - pandas
  - scipy
  - pystan
  - jupyter_contrib_nbextensions
  - fbprophet
  - pip:
    - convertdate
    - holidays
    - plotly


