name: aibs
channels:
  - conda-forge
dependencies:
  - numpy
  - plotly
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - fbprophet
  - jupyter_contrib_nbextensions



